import { FiSettings } from 'react-icons/fi'
import { AiFillTags } from 'react-icons/ai'
import { BiCarousel } from 'react-icons/bi'
import { GrDocument } from 'react-icons/gr'

export default S =>
  S.list()
    .title('Content')
    .items([
      S.listItem()
        .title('Pages')
        .icon(GrDocument)
        .child(
          S.list()
            .title('Pages')
            .showIcons(false)
            .items([
              S.listItem()
                .title('Bio')
                .child(S.document().schemaType('bio').documentId('bio')),
              S.listItem()
                .title('CV')
                .child(S.document().schemaType('cv').documentId('cv')),
              S.listItem()
                .title('Contact')
                .child(
                  S.document().schemaType('contact').documentId('contact'),
                ),
              S.listItem()
                .title('Exhibitions')
                .child(
                  S.document()
                    .schemaType('exhibitions')
                    .documentId('exhibitions'),
                ),
              S.listItem()
                .title('Fellowships')
                .child(
                  S.document()
                    .schemaType('fellowships')
                    .documentId('fellowships'),
                ),
              S.listItem()
                .title('Press')
                .child(S.document().schemaType('press').documentId('press')),
              S.listItem()
                .title('Work')
                .child(S.document().schemaType('work').documentId('work')),
            ]),
        ),
      S.divider(),
      S.listItem()
        .title('Documents')
        .child(
          S.list()
            .title('Documents')
            .id('documentsList')
            .items([
              ...S.documentTypeListItems().filter(
                listItem =>
                  ![
                    'homeCarousel',
                    'bio',
                    'cv',
                    'contact',
                    'exhibitions',
                    'fellowships',
                    'press',
                    'work',
                    'siteSettings',
                    'medium',
                    'material',
                    'collection',
                  ].includes(listItem.getId()),
              ),
            ]),
        ),
      S.listItem()
        .title('Home Carousel')
        .icon(BiCarousel)
        .child(
          S.document().schemaType('homeCarousel').documentId('homeCarousel'),
        ),
      S.listItem()
        .title('Project Filters')
        .icon(AiFillTags)
        .child(
          S.list()
            .title('Filters')
            .showIcons(false)
            .items([
              S.documentTypeListItem('collection'),
              S.documentTypeListItem('material'),
              S.documentTypeListItem('medium'),
            ]),
        ),
      S.divider(),
      S.listItem()
        .title('Settings')
        .icon(FiSettings)
        .child(
          S.document().schemaType('siteSettings').documentId('siteSettings'),
        ),
    ])
